# NOTE, this is meant to be built with {source-root}/tests/dockerfiles as context
FROM python:3.11-slim

WORKDIR /app

RUN pip install flask==2.2.3

COPY ./flask_src /app

CMD ["flask", "run", "--host=0.0.0.0", "--port=80", "--reload"]




