name: Run Tests
run-name: ${{ github.actor }} pushed a change 🚀
on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout
        if: ${{ matrix.python != '3.11' }}
        uses: actions/checkout@v3
      - name: Checkout Full  # needed for pybugsai
        if: ${{ matrix.python == '3.11' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 0 means full depth
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Use Dev Environment Cache
        id: env-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            .venv
            .tox
            .mypy_cache
          key: env-${{ matrix.python }}-${{ hashFiles('setup.py', 'requirements_*.txt') }}
          restore-keys: |
            env-${{ matrix.python }}-
      - name: Install Dev Environment
        if: steps.env-cache.outputs.cache-hit != 'true'
        run: |
          . ./scripts/venv_github.sh
          # it's not necessary to install the whole dev-environment to run tox.  However, this is a good check
          # that the dev-setup works in all python versions
          ./scripts/setup_dev_env.sh
      - name: Run Tox
        id: tox
        run: |
          . ./scripts/venv_github.sh
          ./scripts/tox_github.sh "${{ matrix.python }}"
          echo "result=success" >> "$GITHUB_OUTPUT"
        continue-on-error: true  # want to still save the cache before failing
      - name: Save Dev Environment Cache
        if: steps.env-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            .venv
            .tox
            .mypy_cache
          key: env-${{ matrix.python }}-${{ hashFiles('setup.py', 'requirements_*.txt') }}
      - name: Run PyBugsAI
        if: ${{ matrix.python == '3.11' }}
        uses: ./.github/actions/pybugsai
        with:
          api-key: ${{ secrets.OPEN_AI_API_KEY }}

  results:
      if: ${{ always() }}
      runs-on: ubuntu-latest
      name: Final Results
      needs: [tests]
      steps:
          - run: |
              [[ "${{ needs.tests.result }}" == "success" ]]
