name: Run Tests
run-name: ${{ github.actor }} pushed a change 🚀
on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Use Dev Environment Cache
        uses: actions/cache@v3
        with:
          path: |
            .venv
          key: venv-${{ matrix.python }}-${{ hashFiles('setup.py', 'requirements_*.txt', 'scripts/venv_github.sh', './scripts/setup_dev_env.sh') }}
          restore-keys: |
            venv-${{ matrix.python }}-${{ hashFiles('setup.py', 'requirements_*.txt', 'scripts/venv_github.sh', './scripts/setup_dev_env.sh') }}
            venv-${{ matrix.python }}-
      - name: Install Dev Environment
        run: |
          . ./scripts/venv_github.sh
          # it's not necessary to install the whole dev-environment to run tox.  However, this is a good check
          # that the dev-setup works in all python versions
          ./scripts/setup_dev_env.sh
      - name: Use Tox Cache
        uses: actions/cache@v3
        with:
          path: |
            .tox
            .mypy_cache
          key: tox-${{ matrix.python }}-${{ hashFiles('setup.py', 'requirements_test.txt', 'scripts/venv_github.sh', './scripts/tox_github.sh') }}
          restore-keys: |
              tox-${{ matrix.python }}-${{ hashFiles('setup.py', 'requirements_test.txt', 'scripts/venv_github.sh', './scripts/tox_github.sh') }}
              tox-${{ matrix.python }}-
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: |
          . ./scripts/venv_github.sh
          ./scripts/tox_github.sh "${{ matrix.python }}"
  results:
      if: ${{ always() }}
      runs-on: ubuntu-latest
      name: Final Results
      needs: [tests]
      steps:
          - run: |
              result="${{ needs.tests.result }}"
              if [[ $result == "success"  ]]; then
                exit 0
              else
                exit 1
              fi
